name: "dial_editor_flutter"
version: "1.0.0+1"
publish_to: none
environment:
  sdk: "^3.5.4"
description: A new Flutter project.
dependencies:
  cupertino_icons: "^1.0.8"
  file_picker: ^8.1.3
  flutter:
    sdk: flutter
  flutter_riverpod: "^2.6.1"
  pubspec_dependency_sorter: "^1.0.5"
  tekartik_app_flutter_sembast:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart3a
      path: app_sembast
    version: ">=0.1.0"
  uuid: ^4.5.1
dev_dependencies:
  flutter_lints: "^4.0.0"
  flutter_test:
    sdk: flutter
  very_good_analysis: "^6.0.0"
flutter:
  uses-material-design: true
